import Foundation

enum DashboardLocalization {
    static let table: [String: (String, String)] = [
        "dash.title": ("Dashboards", "لوحات المعلومات"),
        "dash.rows": ("Row count", "عدد الصفوف"),
        "dash.by": ("Rows by", "الصفوف حسب"),
        "dash.name": ("Title", "العنوان"),
        "dash.display.kpi": ("KPI value", "مؤشر رقمي"),
        "dash.display.bar": ("Bar chart", "رسم أعمدة"),
        "dash.display.line": ("Ordered line chart", "رسم خطي مرتب"),
        "dash.display.table": ("Row preview table", "جدول معاينة الصفوف"),
        "dash.metric.count": ("Count rows", "عدد الصفوف"),
        "dash.metric.sum": ("Sum", "المجموع"),
        "dash.metric.average": ("Average", "المتوسط"),
        "dash.metric.minimum": ("Minimum", "الأدنى"),
        "dash.metric.maximum": ("Maximum", "الأعلى"),
        "dash.metric.distinct": ("Distinct values", "القيم المختلفة"),
        "dash.cardType": ("Card type", "نوع البطاقة"),
        "dash.metric": ("Calculation", "الحساب"),
        "dash.group": ("Group / horizontal axis", "التجميع / المحور الأفقي"),
        "dash.editCard": ("Edit card", "تعديل البطاقة"),
        "dash.addCard": ("Add card", "إضافة بطاقة"),
        "dash.options": ("Dashboard options", "خيارات لوحة المعلومات"),
        "dash.refresh": ("Refresh", "تحديث"),
        "dash.matching": ("matching rows", "صف مطابق"),
        "dash.present": ("Presentation mode", "وضع العرض"),
        "dash.editMode": ("Show editing controls", "إظهار أدوات التعديل"),
        "dash.empty": ("empty text", "نص فارغ"),
        "dash.hint": ("All cards share the same filters and source snapshot. Tap a bar/point or use Select group to filter every card. Up to 12 cards, 128 source columns, and a shared 15-second refresh budget. Calculations run locally, without AI.", "تشارك كل البطاقات الفلاتر ولقطة المصدر نفسها. اضغط عمودًا أو نقطة أو استخدم اختيار مجموعة لتصفية كل البطاقات. حتى 12 بطاقة و128 عمودًا ومهلة تحديث مشتركة 15 ثانية. الحسابات محلية دون ذكاء اصطناعي."),
        "dash.numericHint": ("Sum, average, minimum and maximum use stored numeric cells only; text and blanks are ignored, never converted to zero. Use Clean data to convert numeric text first. A dash means no numeric result. Distinct excludes NULL but includes empty text.", "المجموع والمتوسط والأدنى والأعلى تستخدم الخلايا الرقمية المخزنة فقط؛ النص والفراغ يُتجاهلان ولا يتحولان لصفر. استخدم تنظيف البيانات لتحويل النص الرقمي أولًا. الشرطة تعني عدم وجود نتيجة رقمية. القيم المختلفة تستثني NULL وتشمل النص الفارغ."),
        "dash.noNumeric": ("No numeric result", "لا توجد نتيجة رقمية"),
        "dash.barHint": ("Highest 12 groups by value. Tap a bar or select a group below to filter all cards.", "أعلى 12 مجموعة حسب القيمة. اضغط عمودًا أو اختر مجموعة أدناه لتصفية جميع البطاقات."),
        "dash.lineHint": ("First 24 groups sorted by source value. Categories are equally spaced, not a continuous time scale; missing periods are not filled. Use ISO dates for chronological text order. A line joins available numeric points only.", "أول 24 مجموعة مرتبة حسب قيمة المصدر. الفئات متساوية المسافات وليست محورًا زمنيًا مستمرًا، ولا تُملأ الفترات المفقودة. استخدم تواريخ ISO للترتيب الزمني النصي. يصل الخط النقاط الرقمية المتاحة فقط."),
        "dash.selectGroup": ("Select group / inspect values", "اختيار مجموعة / فحص القيم"),
        "dash.sharedFilters": ("Shared filters / search", "الفلاتر / البحث المشتركة"),
        "dash.filterHint": ("Filters affect every card. Search and filters share the grid's matching rules. A selected chart group is an additional exact, type-aware AND condition, even when filters use Match any. Regex is not supported here. Up to 16 filters and 1,000 characters per value.", "تؤثر الفلاتر على كل البطاقات وتتبع قواعد مطابقة الجدول. مجموعة الرسم المحددة شرط إضافي دقيق يراعي النوع ويرتبط بـ AND حتى مع اختيار أي شرط. التعبيرات النمطية غير مدعومة هنا. حتى 16 فلترًا و1000 حرف لكل قيمة."),
        "dash.truncated": ("More results exist. Chart limits: 12 bars / 24 line groups; table: first 50 rows. KPI calculations and the matching-row count cover all matching data.", "توجد نتائج إضافية. الحدود: 12 عمودًا أو 24 مجموعة خطية، وأول 50 صفًا للجدول. حسابات المؤشرات وعدد الصفوف المطابقة تشمل جميع البيانات المطابقة."),
        "dash.saved": ("Dashboard configuration saved. Reopening recomputes current results locally.", "تم حفظ إعدادات اللوحة. إعادة الفتح تعيد حساب النتائج محليًا."),
        "dash.cancelled": ("Refresh cancelled. No partial or stale results are shown.", "أُلغي التحديث. لا تُعرض نتائج جزئية أو قديمة."),
        "dash.unsaved": ("Unsaved dashboard changes", "تغييرات لوحة غير محفوظة"),
        "dash.unsavedHint": ("Close without saving the card layout and filters? Previously saved configuration remains unchanged.", "إغلاق دون حفظ ترتيب البطاقات والفلاتر؟ الإعدادات المحفوظة سابقًا لا تتغير."),
        "dash.discard": ("Discard changes and close", "تجاهل التغييرات والإغلاق"),
        "dash.reset": ("Reset to starter cards", "إعادة البطاقات الافتراضية"),
        "dash.resetHint": ("Replace this draft with starter cards and clear its filters? The saved dashboard changes only when you press Save.", "استبدال المسودة بالبطاقات الافتراضية ومسح فلاترها؟ لا تتغير اللوحة المحفوظة إلا عند الضغط على حفظ."),
        "dash.libraryHint": ("Choose a sheet to create or reopen its dashboard. One saved dashboard per sheet, with up to 12 reorderable KPI, chart and table cards. Join sheets first to analyze combined data. Saving stores configuration, not a frozen report. Pull to refresh this list.", "اختر ورقة لإنشاء لوحتها أو إعادة فتحها. لوحة محفوظة لكل ورقة وحتى 12 بطاقة قابلة للترتيب للمؤشرات والرسوم والجداول. ادمج الأوراق أولًا لتحليل بياناتها معًا. يُحفظ الإعداد وليس تقريرًا ثابتًا. اسحب لتحديث القائمة."),
        "dash.nonFinite": ("A card contains an infinite numeric value or an overflowing calculation. Clean/filter the source or choose a different calculation.", "تحتوي بطاقة على قيمة رقمية غير محدودة أو حساب يتجاوز النطاق. نظّف المصدر أو فلتره أو اختر حسابًا آخر."),
        "dash.invalid": ("Dashboard configuration is invalid, unsupported, or no longer matches this sheet. Check column selections and limits. Reset to starter cards if a saved dashboard cannot be opened; Save explicitly replaces its previous configuration.", "إعداد اللوحة غير صالح أو غير مدعوم أو لم يعد يطابق الورقة. تحقق من الأعمدة والحدود. أعد البطاقات الافتراضية إذا تعذر فتح المحفوظة؛ الحفظ يستبدل إعدادها السابق صراحة."),
        "colors.title": ("About Excel colors", "حول ألوان Excel"),
        "colors.help": ("Enable Show colors in this sheet menu or Settings. Solid cell fills, theme/indexed colors, tints, and detected header fills are supported. Previously omitted or incorrectly imported colors require re-importing the original Excel workbook with Import Excel cell colors enabled; existing sheets are not overwritten. CSV/JSON contain no Excel formatting. Derived sheets are values-only. Conditional formatting, table-style stripes, gradients, font colors and merged-cell layouts are not reproduced. If colors still differ, share a small sample workbook so its formatting can be checked.", "فعّل إظهار الألوان من قائمة الورقة أو الإعدادات. تدعم الألوان المصمتة وألوان السمة والفهرسة والتدرجات اللونية للسمة وتعبئة العناوين المكتشفة. الألوان التي أُهملت أو استُوردت خطأ سابقًا تتطلب إعادة استيراد ملف Excel الأصلي مع تفعيل استيراد ألوان الخلايا؛ لا تُستبدل الأوراق الحالية. CSV وJSON لا يحتويان تنسيق Excel. الأوراق المشتقة قيم فقط. لا يُعاد إنتاج التنسيق الشرطي أو أشرطة أنماط الجداول أو التعبئة المتدرجة أو ألوان الخط أو دمج الخلايا. إذا بقي اختلاف، شارك ملفًا صغيرًا لفحص تنسيقه."),
    ]
}
