import Foundation

enum PreparationLocalization {
    static let table: [String: (String, String)] = [
        "prep.clean": ("Clean data", "تنظيف البيانات"),
        "prep.join": ("Join / lookup", "دمج / بحث مرجعي"),
        "prep.history": ("Preparation history", "سجل تجهيز البيانات"),
        "prep.derived": ("Derived", "ورقة مشتقة"),
        "prep.immutable": ("Your source sheets stay unchanged", "الأوراق الأصلية تبقى دون تغيير"),
        "prep.valuesOnly": ("Works on the entire sheet, not just filtered rows. Results contain values only: source formatting, colors, and formulas are not copied. Everything runs locally; no AI or network is used.", "تُعالج الورقة كاملة، وليس الصفوف المفلترة فقط. النتيجة قيم فقط؛ لا تُنسخ التنسيقات أو الألوان أو الصيغ. المعالجة محلية دون ذكاء اصطناعي أو شبكة."),
        "prep.limits": ("Up to 1 million rows per source/output, 128 output columns, 20 cleaning steps, and 120 seconds per run. Large operations may need substantial free storage.", "حتى مليون صف لكل مصدر أو نتيجة، و128 عمودًا، و20 خطوة تنظيف، و120 ثانية للتنفيذ. قد تتطلب العمليات الكبيرة مساحة تخزين حرة كبيرة."),
        "prep.outputName": ("New sheet name (up to 120 characters)", "اسم الورقة الجديدة (حتى 120 حرفًا)"),
        "prep.saved": ("New sheet saved to My Sheets", "تم حفظ ورقة جديدة في ملفاتي"),
        "prep.open": ("Open new sheet", "فتح الورقة الجديدة"),
        "prep.sampleHint": ("Samples: first 30 rows, up to 4 MiB each. Counts describe the full result. Before/after rows may differ after removal; Source row identifies the original row. A null cell displays as empty.", "العينات: أول 30 صفًا وبحد أقصى 4 ميبيبايت لكل عينة. الأعداد تخص النتيجة الكاملة. قد تختلف الصفوف بعد الحذف؛ رقم صف المصدر يحدد الصف الأصلي. تظهر القيمة الخالية كخلية فارغة."),
        "prep.before": ("Before", "قبل"),
        "prep.after": ("After / joined result", "بعد / نتيجة الدمج"),
        "prep.rejected": ("Invalid conversions — sample (first 10 per step, 30 total)", "تحويلات غير صالحة — عينة (أول 10 لكل خطوة، 30 إجمالًا)"),
        "prep.review": ("Review before saving", "راجع قبل الحفظ"),
        "prep.approveDuplicates": ("I understand repeated right-side keys can expand rows", "أفهم أن تكرار مفاتيح الطرف الأيمن قد يضاعف الصفوف"),
        "prep.approveInvalid": ("Keep original values for invalid conversions", "الاحتفاظ بالقيم الأصلية للتحويلات غير الصالحة"),
        "prep.newOutput": ("Save creates a separate workbook and sheet. The preview is not saved until you press Save new sheet.", "ينشئ الحفظ مصنفًا وورقة مستقلين. لا تُحفظ المعاينة حتى تضغط حفظ ورقة جديدة."),
        "prep.preview": ("Run preview", "تشغيل المعاينة"),
        "prep.save": ("Save new sheet", "حفظ ورقة جديدة"),
        "prep.running": ("Preparing full result… Cancel is available above.", "جارٍ تجهيز النتيجة الكاملة… الإلغاء متاح بالأعلى."),
        "prep.saving": ("Saving atomically… Cancel is available above.", "جارٍ الحفظ كوحدة واحدة… الإلغاء متاح بالأعلى."),
        "prep.cancelled": ("Cancelled. No new sheet was saved.", "تم الإلغاء. لم تُحفظ ورقة جديدة."),
        "prep.recipe": ("Ordered cleaning steps", "خطوات التنظيف بالترتيب"),
        "prep.undoHint": ("Undo/redo edits this recipe, not your source. Tap a step to edit it. An empty recipe makes a values-only copy.", "التراجع والإعادة يعدّلان هذه الوصفة وليس المصدر. اضغط على خطوة لتعديلها. الوصفة الفارغة تنشئ نسخة من القيم فقط."),
        "prep.undo": ("Undo", "تراجع"),
        "prep.redo": ("Redo", "إعادة"),
        "prep.up": ("Earlier", "للأعلى"),
        "prep.down": ("Later", "للأسفل"),
        "prep.addStep": ("Add cleaning step", "إضافة خطوة تنظيف"),
        "prep.joinSources": ("Match sources", "مطابقة المصادر"),
        "prep.leftKey": ("Key in current sheet (left)", "المفتاح في الورقة الحالية (يسار)"),
        "prep.rightSheet": ("Other sheet (right)", "الورقة الأخرى (يمين)"),
        "prep.rightKey": ("Key in other sheet", "المفتاح في الورقة الأخرى"),
        "prep.joinMode": ("Join type", "نوع الدمج"),
        "prep.keyMode": ("Key matching", "مطابقة المفاتيح"),
        "prep.joinHint": ("Left keeps all left rows; Inner keeps matches only. Lookup keeps all left rows but requires unique nonblank right keys. Blanks never match. All left columns are retained. You can also join a sheet to itself.", "الدمج الأيسر يحتفظ بكل صفوف اليسار؛ الداخلي يحتفظ بالتطابقات فقط. البحث المرجعي يحتفظ باليسار ويشترط مفاتيح يمين فريدة غير فارغة. الفراغات لا تتطابق. تُحفظ كل أعمدة اليسار. يمكن دمج الورقة مع نفسها."),
        "prep.exactHint": ("Exact: case-sensitive text; numeric 1 equals numeric 1.0, but text 001 and text 1 stay different from numbers. Whitespace is significant except wholly blank keys.", "دقيق: النص حساس لحالة الأحرف؛ العدد 1 يساوي العدد 1.0، لكن النصين 001 و1 يختلفان عن الأعداد. المسافات مؤثرة إلا في المفاتيح الفارغة بالكامل."),
        "prep.normalizedHint": ("Normalized text: cast numbers to text, trim Unicode whitespace, lowercase, normalize Arabic/Persian digits and Unicode composition. This can merge previously different keys; review duplicate counts.", "نص موحّد: تحويل الأعداد إلى نص، وإزالة المسافات الطرفية، وتوحيد حالة الأحرف والأرقام العربية والفارسية وتركيب Unicode. قد تتطابق مفاتيح كانت مختلفة؛ راجع أعداد التكرار."),
        "prep.rightColumns": ("Columns to bring from the right sheet", "الأعمدة المطلوبة من ورقة اليمين"),
        "prep.join.left": ("Left join — keep all left rows", "دمج أيسر — الاحتفاظ بكل اليسار"),
        "prep.join.inner": ("Inner join — matching rows only", "دمج داخلي — المتطابق فقط"),
        "prep.join.lookup": ("Strict lookup — unique right key", "بحث مرجعي — مفتاح يمين فريد"),
        "prep.key.exact": ("Exact (type-aware)", "دقيق (يراعي نوع القيمة)"),
        "prep.key.normalizedText": ("Normalized text", "نص موحّد"),
        "prep.operation": ("Operation", "العملية"),
        "prep.column": ("Column", "العمود"),
        "prep.find": ("Find literal text", "البحث عن نص حرفي"),
        "prep.replace": ("Replace with (may be empty)", "الاستبدال بـ (يمكن تركه فارغًا)"),
        "prep.literalHint": ("Case-sensitive, literal replacement in text cells only; not a regular expression.", "استبدال حرفي حساس لحالة الأحرف في الخلايا النصية فقط، وليس تعبيرًا نمطيًا."),
        "prep.fillValue": ("Literal text to fill blanks", "نص حرفي لملء الفراغات"),
        "prep.fillHint": ("Fill values are always text, including 0. Add a number-conversion step afterwards if needed.", "قيمة الملء نص دائمًا، حتى 0. أضف خطوة تحويل رقمي بعدها عند الحاجة."),
        "prep.numberFormat": ("Number separators", "فواصل الأعداد"),
        "prep.numberHint": ("Converts text using the selected separators and strict grouping. Leading zeros are removed. Integers must fit Int64; decimals/scientific notation allow up to 15 significant digits. Invalid values remain unchanged and are counted.", "يحوّل النص وفق الفواصل المختارة مع تحقق صارم من تجميع الآلاف. تُحذف الأصفار البادئة. الأعداد الصحيحة ضمن Int64، والعشرية أو العلمية حتى 15 رقمًا ذا دلالة. القيم غير الصالحة تبقى كما هي وتُحصى."),
        "prep.number.dotDecimal": ("1,234.56 — dot decimal", "1,234.56 — نقطة عشرية"),
        "prep.number.commaDecimal": ("1.234,56 — comma decimal", "1.234,56 — فاصلة عشرية"),
        "prep.number.arabic": ("١٬٢٣٤٫٥٦ — Arabic separators", "١٬٢٣٤٫٥٦ — فواصل عربية"),
        "prep.dateFormat": ("Exact input date format", "تنسيق تاريخ الإدخال الدقيق"),
        "prep.dateHint": ("Gregorian dates only. Output is yyyy-MM-dd in UTC. No guessing, Excel serial-date conversion, or time-of-day parsing. Invalid dates stay unchanged.", "تواريخ ميلادية فقط. الناتج yyyy-MM-dd بتوقيت UTC. لا تخمين ولا تحويل لأرقام تاريخ Excel ولا تحليل للوقت. التواريخ غير الصالحة تبقى كما هي."),
        "prep.missingHint": ("Missing means NULL, empty text, or Unicode whitespace only. Text operations preserve numeric cells. Deduplicate compares the entire row and keeps its first occurrence.", "المفقود هو NULL أو نص فارغ أو مسافات Unicode فقط. العمليات النصية لا تغير الخلايا الرقمية. إزالة التكرار تقارن الصف كاملًا وتحتفظ بأول ظهور."),
        "prep.editStep": ("Edit cleaning step", "تعديل خطوة التنظيف"),
        "prep.clean.trim": ("Trim Unicode whitespace", "إزالة المسافات الطرفية"),
        "prep.clean.normalizeDigits": ("Arabic/Persian digits → 0–9", "توحيد الأرقام العربية والفارسية إلى 0–9"),
        "prep.clean.lowercase": ("Lowercase text", "أحرف صغيرة"),
        "prep.clean.uppercase": ("Uppercase text", "أحرف كبيرة"),
        "prep.clean.replaceText": ("Replace literal text", "استبدال نص حرفي"),
        "prep.clean.fillMissing": ("Fill missing with text", "ملء القيم المفقودة بنص"),
        "prep.clean.blankToNull": ("Blank text → NULL", "النص الفارغ إلى NULL"),
        "prep.clean.parseNumber": ("Convert to number (strict)", "تحويل إلى عدد (صارم)"),
        "prep.clean.parseDate": ("Convert to ISO date (strict)", "تحويل إلى تاريخ ISO (صارم)"),
        "prep.clean.dropMissing": ("Drop rows missing this column", "حذف الصفوف التي تفتقد هذا العمود"),
        "prep.clean.removeDuplicates": ("Remove duplicate whole rows", "إزالة تكرار الصفوف الكاملة"),
        "prep.summary": ("Full-result diagnostics", "تشخيص النتيجة الكاملة"),
        "prep.outputRows": ("Output rows", "صفوف النتيجة"),
        "prep.leftRows": ("Left source rows", "صفوف مصدر اليسار"),
        "prep.rightRows": ("Right source rows", "صفوف مصدر اليمين"),
        "prep.matchedLeft": ("Matched left rows", "صفوف اليسار المتطابقة"),
        "prep.unmatchedLeft": ("Unmatched left rows", "صفوف اليسار غير المتطابقة"),
        "prep.unmatchedRight": ("Unmatched right rows", "صفوف اليمين غير المتطابقة"),
        "prep.blankLeft": ("Blank left keys", "مفاتيح اليسار الفارغة"),
        "prep.blankRight": ("Blank right keys", "مفاتيح اليمين الفارغة"),
        "prep.duplicateLeft": ("Repeated left key groups", "مجموعات مفاتيح اليسار المتكررة"),
        "prep.duplicateRight": ("Repeated right key groups", "مجموعات مفاتيح اليمين المتكررة"),
        "prep.changed": ("Changed cells", "خلايا تغيرت"),
        "prep.removed": ("Removed rows", "صفوف أُزيلت"),
        "prep.invalid": ("Invalid conversions retained", "تحويلات غير صالحة احتُفظ بأصلها"),
        "prep.sourceRow": ("Source row", "صف المصدر"),
        "prep.historyHint": ("Saved recipes let you edit and rebuild into another new sheet. Existing outputs never change and remain usable after deleting a source. Rebuilding requires the original sources and matching schemas. Unsaved drafts are not restored after closing.", "تتيح الوصفات المحفوظة التعديل وإعادة البناء في ورقة جديدة أخرى. النتائج السابقة لا تتغير وتبقى قابلة للاستخدام بعد حذف المصدر. إعادة البناء تتطلب المصادر الأصلية وبنيتها المطابقة. المسودات غير المحفوظة لا تُستعاد بعد الإغلاق."),
        "prep.rebuild": ("Edit recipe & rebuild a new copy", "تعديل الوصفة وبناء نسخة جديدة"),
        "prep.noHistory": ("This is an imported sheet. Clean or join it to create a derived sheet with saved history.", "هذه ورقة مستوردة. نظّفها أو ادمجها لإنشاء ورقة مشتقة بسجل محفوظ."),
        "prep.error.recipe": ("Invalid or unsupported recipe. Check columns, step parameters, and output name. Joins need at least one right-side output column and at most 128 total columns.", "وصفة غير صالحة أو غير مدعومة. تحقق من الأعمدة ومعلمات الخطوات والاسم. يتطلب الدمج عمودًا واحدًا على الأقل من اليمين وبحد أقصى 128 عمودًا إجمالًا."),
        "prep.error.source": ("A source is missing or its schema/row count changed. Existing derived sheets are safe; choose current sources and create a new recipe.", "أحد المصادر مفقود أو تغيرت بنيته أو عدد صفوفه. الأوراق المشتقة السابقة آمنة؛ اختر مصادر حالية وأنشئ وصفة جديدة."),
        "prep.error.sourceLimit": ("Preparation supports up to 1 million rows per source.", "يدعم التجهيز حتى مليون صف لكل مصدر."),
        "prep.error.outputLimit": ("This result exceeds 1 million rows or is not ready to save. Reduce duplicate keys or use a smaller source.", "تتجاوز النتيجة مليون صف أو ليست جاهزة للحفظ. قلّل المفاتيح المكررة أو استخدم مصدرًا أصغر."),
        "prep.error.lookup": ("Lookup blocked: the right key contains duplicates. Clean/deduplicate the right source, or choose Left/Inner join and explicitly review expansion.", "تعذر البحث المرجعي: مفتاح اليمين مكرر. نظّف مصدر اليمين أو أزل تكراره، أو اختر الدمج الأيسر أو الداخلي وراجع تضاعف الصفوف صراحة."),
        "prep.error.approveDuplicates": ("Review and approve possible row expansion before saving.", "راجع ووافق على احتمال تضاعف الصفوف قبل الحفظ."),
        "prep.error.approveInvalid": ("Review and approve keeping original invalid values before saving.", "راجع ووافق على إبقاء القيم الأصلية غير الصالحة قبل الحفظ."),
        "prep.error.valueLimit": ("A transformed value exceeds 1 MiB. Use a smaller replacement or smaller values.", "تتجاوز قيمة بعد التحويل 1 ميبيبايت. استخدم استبدالًا أقصر أو قيمًا أصغر."),
        "prep.error.storage": ("Preparation ran out of working storage. Free space or use smaller sources.", "نفدت مساحة العمل للتجهيز. أفرغ مساحة أو استخدم مصادر أصغر."),
        "prep.error.timeout": ("Preparation exceeded 120 seconds. Try fewer steps or smaller sources. No new sheet was saved.", "تجاوز التجهيز 120 ثانية. جرّب خطوات أقل أو مصادر أصغر. لم تُحفظ ورقة جديدة."),
    ]
}
